version: '3'
services:
  kanban-postgres:
    image: "postgres:9.6-alpine"
    volumes:
      - kanban-data10:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=kanban10
      - POSTGRES_USER=kanban10
      - POSTGRES_PASSWORD=kanban10
  kanban-app-01:
    image: "docker.io/nreljin/wbi-devops-task-backend"
    environment:
      - DB_SERVER=kanban-postgres
      - POSTGRES_DB=kanban10
      - POSTGRES_USER=kanban10
      - POSTGRES_PASSWORD=kanban10
    ports:
      - 8081:8080
  kanban-app-02:
    image: "docker.io/nreljin/wbi-devops-task-backend"
    environment:
      - DB_SERVER=kanban-postgres
      - POSTGRES_DB=kanban10
      - POSTGRES_USER=kanban10
      - POSTGRES_PASSWORD=kanban10
    ports:
      - 8082:8080
  kanban-app:
    image: nginx
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  kanban-ui:
    image: "docker.io/nreljin/wbi-devops-task-frontend"
    ports:
      - 4200:80
volumes:
  kanban-data10:
